### ISSUE TITLE
Different line height between Firefox and Chrome

### ISSUE THREAD

**Issue by xfalcox** [jxnblk/fitter-happier-text#18]
Guys, we're trying to use this plugin and found huge line height difference between browsers.

Any tips?

![fitter](https://cloud.githubusercontent.com/assets/1385470/8286539/8c1f7d10-18e0-11e5-8281-eb39183fca08.png)

**Comment by kennethormandy** [comment]
Good catch. The demo page [uses Avenir Next](https://github.com/jxnblk/fitter-happier-text/blob/667817cacfc28888260980079523ebdb0fd78c39/index.html#L9), which is only a system font on relatively reecnty versions of OS X. On other browsers it’s falling back to whatever maps to `sans-serif`, which looks like it’s to different fonts between Firefox and Chrome for you, hence the different line heights.

If the typefaces were the same, or if you give things a try locally with a different font, I don’t think this would be an issue.

**Comment by jxnblk** [comment]
That might be what's happening. It looks like Firefox also handles letter spacing differently, which would cause the SVG to appear larger and affect the line height.

@xfalcox what version of Firefox is this screenshot? And can you share the styling that it's inheriting?

**Comment by xfalcox** [comment]
I'll try to get some screenshots at work tomorrow, because we found this using a webfont, probably Lato, and had to pull back some code because since line height was much bigger on firefox (latest or FF16 our target) text was getting cropped since the parent div has a max height.

**Comment by xfalcox** [comment]
@jxnblk It's just the [plugin page](http://jxnblk.com/fitter-happier-text/) on latest chrome and firefox. What's worst for us is the space between lines (look after AT EASE line).

**Comment by xfalcox** [comment]
Found this:

No letter spacing on Firefox on SVG (https://bugzilla.mozilla.org/show_bug.cgi?id=371787)

**Comment by jchck** [comment]
@xfalcox have you found a work around for this? I'm experiecing it too.

**Comment by xfalcox** [comment]
We gave up =(

Currently a coworker wrote a using canvas, but it's kinda CPU heavy.

**Comment by jchck** [comment]
That's not promising.

**Comment by jchck** [comment]
This seems to be related to a discrepancy in how the svg viewBox attribute is being calculated. 

ie: a heading viewed on webkit has an svg viewBox="0 0 92 12" while the same heading viewed on moz has an svg viewBox="0 0 91.6666 26".
